default_install_hook_types: ['pre-commit', 'commit-msg']
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: '.github'
      - id: check-ast
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-case-conflict

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-isort
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py39-plus]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
      - id: yapf
        name: yapf
        entry: yapf
        language: python
        types: [python]
        args: ["-i"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
